# Generated by Django 2.2.5 on 2019-09-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='duration',
            new_name='man_hours',
        ),
    ]
